# Generated by Django 3.1.1 on 2020-10-25 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField()),
                ('isbn_number', models.CharField(max_length=13)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('cover_link', models.URLField()),
                ('language', models.CharField(max_length=3)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
